### ISSUE TITLE
External url loading in (youtube /IFRAME)

### ISSUE THREAD

**Issue by dzkanch** [dixso/custombox#170]
Hi there,
is it possible to have modal box load url(external link / youtube ) in iframe 

i have done the module, so this area is missing. and its important to load url in iframe,

your plugin inspired me alot and i am thinking to use in Joomla/wordpress 
i am not good in Javascript/jQuery -

please let me know, so i can finalize the module,

Thank you

**Comment by dixso** [comment]
Hi,
Only you can put the iframe in the div without use Ajax.
Regards.

**Comment by dzkanch** [comment]
what about Youtube/Vimeo

**Comment by cptx032** [comment]
Is like that
http://codepen.io/anon/pen/jWYPdP
?

**Comment by dzkanch** [comment]
yes.
but video link has to be in <a href=""/>  not inline.

example : 
<a href="http://youtube.com/?watch=2SD3dRsd" >show modal</a>

**Comment by dzkanch** [comment]
@cptx032  your example is good. but this isnt solution.

if you figure out the fancybox you'll understand.

**Comment by cowboysdude** [comment]
Yes if this could work with youtube videos it would truly awesome! Love the work you've done!  I have also written a 'module' for joomla that opens a modal for youtube videos but I don't distribute my videos I use it strictly on my own site... frustrated with the whole open source thing.  Everyone trying to make a buck on other people instead of helping them.  This is why you guys who write these awesome plugins are helping keep that alive!  Thank you!

**Comment by dzkanch** [comment]
well in joomla i figure out. for a single youtube video.. i need to add the reg expr to detect the youtube url.
and then create a wrapper for it and calling it like inline content model opening.. :)

**Comment by dixso** [comment]
Hi,
Try the new RC: https://github.com/dixso/custombox/tree/master/dist
Regards
