### ISSUE TITLE
iframe reload on open/close custombox

### ISSUE THREAD

**Issue by ronirigoni** [dixso/custombox#183]
Hi!
I'm having problems with an unwanted iframe reload, everytime I open or close a custombox. Here is an example: http://codepen.io/anon/pen/repYKE

Why is that happening? Is there a way to prevent this reload?

Thanks,

**Comment by dixso** [comment]
Hi,
https://github.com/dixso/custombox/issues/174

**Comment by ronirigoni** [comment]
@dixso 

Adding 'Custombox.set({ autobuild: true })' before open the custombox didn't work in this case, as you can test with the example code I've sent.

**Comment by dixso** [comment]
Hi,
`<script type="text/javascript">
  Custombox.set({ autobuild: true });
  function show_modal() {
    Custombox.open({target: '#message'});
  }
</script>`

**Comment by Teppichratte** [comment]
I have the same problem with different iframes, for example a youtube iframe.
Everytime I open or close a modal window, the iframes get reloaded which is very annoying.
This problem didn't occur in the previous version v1.1.3.

**Comment by Teppichratte** [comment]
Hi dixso, it's me again. Unfortunately I haven't heard from you since my last posting.

I've modified the example from user "ronirigoni" (see above) and added "Custombox.set({ autobuild: true });" before the show_modal() function.The effect is that when you open the custombox for the first time, the iframe doesn't get reloaded BUT (!!!) when you close the modal window and open it again, then the iframe gets reloaded again so your solution only works for the FIRST CALL.

I have also used this solution in my project with an youtube iframe. When I open the modal window for the first time, the iframe doesn't get reloaded BUT when i close the modal window then the iframe gets reloaded again.

This bug makes our wegpage unusable. Can you please provide a bugfix soon???

**Comment by ronirigoni** [comment]
@Teppichratte 

Because of this issue I don't use this lib anymore. Now I use the Lity (http://sorgalla.com/lity/), that is ultra-lightweight and is working perfect for me. Give it a try.

Regards,

**Comment by Teppichratte** [comment]
Hi Roni, I've visited the page but it seems it doesn't fulfil our requirements, for example I couldn't find the effects or event handlers.

The old version of CustomBox didn't have this BUG but instead it had some paiting problems. When a modal window was opened the elements (buttons etc) inside the modal window very drawn incorrect. For example when you put the mouse pointer over a button the button suddenly gain 1px height.

I hope they fix the bug soon because otherwise we also have to look for alternatives.
