### ISSUE TITLE
custombox container setting

### ISSUE THREAD

**Issue by xuanchenglee** [dixso/custombox#228]
I just created the modal variable, and i want to set the container property for it, I tried a lot format for it ,Id or class name. But it seems like nothing work. 
Following is one of example that does nothing:
 new Custombox.modal({
	content: {
		target: '#job_info_modal',
		container: '.content',

**Comment by dixso** [comment]
Hi,
Could you put an example in [jsfiddle.net](jsfiddle.net)?

Regards

**Comment by xuanchenglee** [comment]
I tried to put the example in jsfiddle. But the example does not work because it includes other library.What i want to know the usage of the container property for custom box.

The problem what I am placing is that when I place a YouTube video inside the custom box modal, and click on the full screen. The screen is not working properly. It contains the other element on the page in the full screen view. But this kind of issue did not appear on the old version of custombox 3.0.0.  I have compared these two versions, the only difference is that new version does not contain custombox container tag in the HTML code. And we can set the container property in custombox class, I tried to create a custombox container something. But nothing works. What I want to know is that How do I set for container property?

**Comment by xuanchenglee** [comment]
here is the jsffiddle example i just created:
https://jsfiddle.net/sjjuge2/oqdb32h4/3/

You click the button, the modal contains a youtube video, then you play it, and double click it to make it full screen, it will not really become "full screen", it also show up the button in the page.

I set up the container property in the custombox class, it seem like it does not work in this example. Just please help me to figure out the container property or alternative way to avoid the full screen issue.

Thanks.

**Comment by dixso** [comment]
Hi @xuanchenglee ,
I think is a bug, I'll check it.

Regards.

**Comment by xuanchenglee** [comment]
Thanks, please let me know if you find out any solution for this.

**Comment by dixso** [comment]
Hi @xuanchenglee ,
Solved in the next release (coming soon).

Regards.

**Comment by smarterdigitalltd** [comment]
Hello

I am not the original poster of this issue, but I have the same problem.

Perhaps I am misunderstanding the use of the container property, but I cannot see what effect it has.

I have upgraded to 4.0.2, and have specified

```
container: #someElement
```

but it does not do anything - it is the same as 4.0.1

I had expected it to attach the modal to #someElement (which exists in the DOM).

I have read the documentation again, and it says **Set the element (ID or Class) of the container _page_** and I don't know what 'page' means, which is why maybe I am misunderstanding this property.

Could you please clarify if 1) I am misunderstanding, or 2) If this bugfix did not make it to 4.0.2?

Thank you in advance :)

**Comment by dixso** [comment]
Hi @smarterdigitalltd ,
The problem was the fullscreen into the video.
The property _container_ is used for some types of effect, for example the push effect.
Maybe you're right that the documentation don't explain very well.
