### ISSUE TITLE
Not work!

### ISSUE THREAD

**Issue by chascos69** [dixso/custombox#91]
I download the zip, open index and not work..

**Comment by dixso** [comment]
Not running because need apache o other because need the "http", if need running with "file:///", replace:
"// by "http:// and insert the route relative:
<pre>&lt;link rel="stylesheet" href="demo/css/demo.css"></pre> by <pre>&lt;link rel="stylesheet" href="./demo/css/demo.css"></pre>
-
<pre>&lt;link rel="stylesheet" href="/dist/custombox.min.css"></pre> by <pre>&lt;link rel="stylesheet" href="./dist/custombox.min.css"></pre>
-
<pre>&lt;script src="/dist/custombox.min.js"></script></pre> by <pre>&lt;script src="./dist/custombox.min.js"></script></pre>
-
<pre>&lt;script src="/dist/legacy.min.js"></script></pre> by <pre>&lt;script src="./dist/legacy.min.js"></script></pre>
-
<pre>&lt;script src="demo/js/demo.js"></script></pre> by <pre>&lt;script src="./demo/js/demo.js"></script></pre>
